### ISSUE TITLE
Data set distinction

### ISSUE THREAD

**Issue by hawkins** [EliCDavis/PyChart#5]
It would be nice to see data sets distinguished in final results. Maybe different colors between data sets, have them labeled in the tooltip, etc. Could this be done by including custom generated CSS to the generated HTML page?

**Comment by EliCDavis** [comment]
Colors have been added as of [this commit](https://github.com/EliCDavis/PyChart/commit/baa44e6198849010578baa4e00d7840269f9aeaa).  Adding files in the export dependencies, and then modifying the export header method would work for users defining what css they'd like.
